name: macOS Universal Build
on: [workflow_dispatch, push]
jobs:
 build:
  runs-on: macos-15
  steps:
   - uses: actions/checkout@v4
   - name: Configure
     run: cmake -S . -B build -G Xcode -DCMAKE_BUILD_TYPE=Release
   - name: Build
     run: cmake --build build --config Release --target Timber_VST3 Timber_AU Timber_Standalone
   - uses: actions/upload-artifact@v4
     with:
      name: Timber-macOS-universal
      path: build/Timber_artefacts/Release/
